# Generated by Django 3.0.1 on 2020-11-28 19:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_type', models.CharField(max_length=30)),
                ('access_token', models.CharField(max_length=60, unique=True)),
                ('refresh_token', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('expires_in', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=63, null=True)),
                ('resource_state', models.IntegerField(null=True)),
                ('firstname', models.CharField(blank=True, max_length=63)),
                ('lastname', models.CharField(blank=True, max_length=63)),
                ('city', models.CharField(blank=True, max_length=63, null=True)),
                ('state', models.CharField(blank=True, max_length=63, null=True)),
                ('country', models.CharField(blank=True, max_length=63, null=True)),
                ('sex', models.CharField(blank=True, max_length=1)),
                ('badge_type_id', models.IntegerField(null=True)),
                ('profile_medium', models.URLField(blank=True)),
                ('profile', models.URLField(blank=True)),
                ('token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StravaAnalyzer.Token')),
                ('activities_fetched', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='SummaryReport',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('summary_type', models.CharField(choices=[('A', 'Annual'), ('Q', 'Quarterly'), ('M', 'Monthly'), ('W', 'Weekly')], max_length=1)),
                ('dt_start', models.DateTimeField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('week', models.IntegerField(null=True)),
                ('dt_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryTable',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('sport_type', models.CharField(max_length=30)),
                ('total_elapsed_time', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StravaAnalyzer.SummaryReport')),
            ],
            options={
                'ordering': ['-total_elapsed_time'],
            },
        ),
        migrations.CreateModel(
            name='SummaryRow',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('total_activity_count', models.IntegerField()),
                ('total_elapsed_time', models.IntegerField()),
                ('total_distance', models.FloatField(null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StravaAnalyzer.Athlete')),
                ('summarytable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StravaAnalyzer.SummaryTable')),
            ],
            options={
                'ordering': ['-total_elapsed_time'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('distance', models.FloatField(null=True)),
                ('moving_time', models.IntegerField(null=True)),
                ('elapsed_time', models.IntegerField(null=True)),
                ('total_elevation_gain', models.FloatField(null=True)),
                ('start_latitude', models.FloatField(null=True)),
                ('start_longitude', models.FloatField(null=True)),
                ('end_latitude', models.FloatField(null=True)),
                ('end_longitude', models.FloatField(null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=60)),
                ('utc_offset', models.IntegerField(null=True)),
                ('athlete_count', models.IntegerField(null=True)),
                ('map_id', models.CharField(blank=True, max_length=30)),
                ('map_summary_polyline', models.CharField(blank=True, max_length=400)),
                ('manual', models.BooleanField()),
                ('average_speed', models.FloatField(null=True)),
                ('max_speed', models.FloatField(null=True)),
                ('achievement_count', models.IntegerField(null=True)),
                ('pr_count', models.IntegerField(null=True)),
                ('average_cadence', models.FloatField(null=True)),
                ('average_temp', models.FloatField(null=True)),
                ('has_heartrate', models.BooleanField()),
                ('average_heartrate', models.FloatField(null=True)),
                ('max_heartrate', models.FloatField(null=True)),
                ('elev_high', models.FloatField(null=True)),
                ('elev_low', models.FloatField(null=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StravaAnalyzer.Athlete')),
                ('runner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NavigantAnalyzer.Runner')),
                ('workout_type', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryColumn',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('column_number', models.IntegerField()),
                ('dt_start', models.DateTimeField(blank=True, null=True)),
                ('period', models.CharField(max_length=8)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StravaAnalyzer.SummaryReport')),
                ('dt_end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySummary',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('summary_type', models.CharField(choices=[('A', 'Annual'), ('Q', 'Quarterly'), ('M', 'Monthly'), ('W', 'Weekly')], max_length=1)),
                ('sport_type', models.CharField(max_length=30)),
                ('dt_start', models.DateTimeField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('week', models.IntegerField(null=True)),
                ('activity_count', models.IntegerField()),
                ('sum_elapsed_time', models.IntegerField()),
                ('sum_distance', models.FloatField(null=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StravaAnalyzer.Athlete')),
                ('runner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NavigantAnalyzer.Runner')),
                ('dt_end', models.DateTimeField(blank=True, null=True)),
                ('rank_distance', models.IntegerField(null=True)),
                ('rank_time', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryCell',
            fields=[
                ('id', models.CharField(max_length=62, primary_key=True, serialize=False)),
                ('column_number', models.IntegerField()),
                ('activity_count', models.IntegerField(null=True)),
                ('sum_elapsed_time', models.IntegerField(null=True)),
                ('sum_distance', models.FloatField(null=True)),
                ('summaryrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StravaAnalyzer.SummaryRow')),
                ('dt_end', models.DateTimeField(blank=True, null=True)),
                ('dt_start', models.DateTimeField(blank=True, null=True)),
                ('rank_distance', models.IntegerField(null=True)),
                ('rank_time', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SummaryTotal',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('summary_type', models.CharField(choices=[('A', 'Annual'), ('Q', 'Quarterly'), ('M', 'Monthly'), ('W', 'Weekly')], max_length=1)),
                ('sport_type', models.CharField(max_length=30)),
                ('dt_start', models.DateTimeField(blank=True, null=True)),
                ('dt_end', models.DateTimeField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('week', models.IntegerField(null=True)),
                ('avg_activity_count', models.FloatField()),
                ('avg_elapsed_time', models.IntegerField()),
                ('avg_distance', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColumnTotal',
            fields=[
                ('id', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('avg_activity_count', models.FloatField(null=True)),
                ('avg_elapsed_time', models.IntegerField(null=True)),
                ('avg_distance', models.FloatField(null=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StravaAnalyzer.SummaryColumn')),
                ('summarytable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StravaAnalyzer.SummaryTable')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
